name: CI - order-service

on:
  push:
    paths:
      - "order-service/**"
      - ".github/workflows/order-service.yml"
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/order-service:latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./order-service
          push: true
          tags: ${{ env.IMAGE }}

      - name: Deploy to Kubernetes (optional)
        if: ${{ secrets.KUBE_CONFIG != '' }}
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        run: |
          echo "$KUBECONFIG_DATA" | base64 --decode > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          kubectl set image deployment/order-service order-service=${{ env.IMAGE }}
          kubectl rollout status deployment/order-service --timeout=120s
